// Connector health model. A live connector (generated / researched / hosted) can
// drift: its endpoint moves, the app's UI changes under a scraper, a token expires,
// the tunnel dies. The health monitor re-verifies live connectors on a schedule and
// folds each probe result into a durable health record so the product can show
// honest status and auto-repair a generated connector before the user notices.
//
// This module is pure (no I/O): it decides state transitions from a probe result.
// The route/cron does the actual re-verify and, on sustained drift of a generated
// connector, the regenerate.

export type HealthState = "healthy" | "drifted" | "unreachable";

export interface ConnectorHealth {
  state: HealthState;
  checkedAt: number;
  consecutiveFailures: number;
  lastOkAt?: number;
  detail?: string;
}

// The distilled outcome of one real read of the connector (from verifyConnector).
export interface HealthProbe {
  ok: boolean;
  status?: number;
  detail?: string;
}

// Fold a fresh probe into the prior health. A 4xx (endpoint moved / auth rejected /
// shape gone) is "drifted" (the connector answered but wrongly, so regeneration may
// help); a network failure or 5xx is "unreachable" (down, retry later). A success
// resets the failure streak and stamps lastOkAt.
export function nextHealth(prior: ConnectorHealth | undefined, probe: HealthProbe, now: number): ConnectorHealth {
  if (probe.ok) {
    return { state: "healthy", checkedAt: now, consecutiveFailures: 0, lastOkAt: now, detail: probe.detail };
  }
  const drifted = typeof probe.status === "number" && probe.status >= 400 && probe.status < 500;
  return {
    state: drifted ? "drifted" : "unreachable",
    checkedAt: now,
    consecutiveFailures: (prior?.consecutiveFailures ?? 0) + 1,
    lastOkAt: prior?.lastOkAt,
    detail: probe.detail,
  };
}

export type ConnectorKind = "generated" | "researched" | "hosted";

// Auto-repair (regenerate a fresh typed bundle) fires only for a GENERATED connector
// that has drifted (answered wrongly, not merely gone offline) for at least
// `threshold` consecutive checks. A one-off blip or a transient outage never triggers
// a regenerate; a researched/hosted connector can't be regenerated by NodeWorm, so it
// is only flagged. Being offline ("unreachable") is not drift: regenerating code
// won't bring a dead host back, so we wait for it to answer wrongly first.
export function shouldAutoRepair(kind: ConnectorKind, health: ConnectorHealth, threshold = 2): boolean {
  return kind === "generated" && health.state === "drifted" && health.consecutiveFailures >= threshold;
}
