// Curated knowledge base of well-known apps and their real integration surface.
// The Scout consults this first. Unknown apps fall through to heuristics (and,
// when NodeWorm is keyed, to live LLM discovery).

import type { AuthType, PortalAutomation } from "./types";

export interface KnowledgeEntry {
  match: string[]; // lowercase names / domains the Scout matches against
  appName: string;
  category: string;
  blurb: string;
  hasPublicApi: boolean;
  apiType: "rest" | "graphql" | "grpc" | "sdk" | "none" | "unknown";
  authType: AuthType;
  authMethods: AuthType[];
  hasHostedMcp: boolean;
  mcpName?: string;
  mcpTransport?: "sse" | "stdio" | "http";
  docsUrl?: string;
  developerPortalUrl?: string;
  loginUrl?: string; // real browser auth screen for a managed session (login form / QR web client)
  noWebClient?: boolean; // app has no browser login at all (e.g. Signal); managed session not viable
  oauthAuthorizeUrl?: string;
  oauthTokenUrl?: string;
  hasWebhooks: boolean;
  rateLimited?: boolean;
  ipRestricted?: boolean;
  twoFactor?: boolean;
  scopes?: string[];
  entities?: string[];
  quirks?: string[];
  outbound?: string[]; // example write actions
  portalAutomation?: PortalAutomation; // honest ToS/account-risk for automating this app's dev portal
}

export const KNOWLEDGE: KnowledgeEntry[] = [
  {
    match: ["stripe", "stripe.com"],
    appName: "Stripe",
    portalAutomation: {
      risk: "medium",
      allowAutomation: true,
      caveat:
        "NodeWorm can drive your own Stripe dashboard to set up Connect. Stripe's terms do not prohibit automating your own account, but they do bar circumventing technical controls, so an automated session is unsupported and low-but-non-zero risk. You can also create the app yourself and paste the Connect client id and secret instead.",
    },
    category: "Payments",
    blurb: "Online payment processing for internet businesses.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "apikey",
    authMethods: ["apikey"],
    hasHostedMcp: true,
    mcpName: "stripe (official)",
    mcpTransport: "http",
    docsUrl: "https://docs.stripe.com/api",
    developerPortalUrl: "https://dashboard.stripe.com/apikeys",
    oauthAuthorizeUrl: "https://connect.stripe.com/oauth/authorize",
    oauthTokenUrl: "https://connect.stripe.com/oauth/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["charges:read", "charges:write", "customers:read", "customers:write", "invoices:write"],
    entities: ["Customer", "Charge", "Invoice", "Subscription", "PaymentIntent"],
    outbound: ["create_customer", "create_invoice", "refund_charge", "list_subscriptions"],
    quirks: ["Use a restricted key, not the live secret, for least privilege."],
  },
  {
    match: ["notion", "notion.so"],
    appName: "Notion",
    category: "Docs / Knowledge",
    blurb: "Connected workspace for notes, docs and databases.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: true,
    mcpName: "notion (official)",
    mcpTransport: "http",
    docsUrl: "https://developers.notion.com/reference",
    developerPortalUrl: "https://www.notion.so/my-integrations",
    oauthAuthorizeUrl: "https://api.notion.com/v1/oauth/authorize",
    oauthTokenUrl: "https://api.notion.com/v1/oauth/token",
    hasWebhooks: false,
    rateLimited: true,
    scopes: ["read_content", "insert_content", "update_content", "read_databases"],
    entities: ["Page", "Database", "Block", "User"],
    outbound: ["create_page", "append_block", "query_database", "update_page"],
    quirks: ["No webhooks: inbound sync is polling or entity mirror.", "Pages must be shared with the integration before they are visible."],
  },
  {
    match: ["slack", "slack.com"],
    appName: "Slack",
    category: "Messaging",
    blurb: "Team messaging and collaboration.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: true,
    mcpName: "slack",
    mcpTransport: "http",
    docsUrl: "https://api.slack.com/methods",
    developerPortalUrl: "https://api.slack.com/apps",
    oauthAuthorizeUrl: "https://slack.com/oauth/v2/authorize",
    oauthTokenUrl: "https://slack.com/api/oauth.v2.access",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["chat:write", "channels:read", "channels:history", "users:read"],
    entities: ["Channel", "Message", "User"],
    outbound: ["post_message", "list_channels", "react", "upload_file"],
    quirks: ["Events API delivers inbound activity via webhooks (URL verification handshake required)."],
  },
  {
    match: ["gmail", "google mail", "mail.google.com"],
    appName: "Gmail",
    portalAutomation: {
      risk: "medium",
      allowAutomation: true,
      caveat:
        "NodeWorm can drive your own Google Cloud Console to create the OAuth client. Google's API terms allow this as long as you act as yourself (no masked identity), but Google's login bot-detection may challenge an automated session and the flow is unsupported. Proceed on your own account, or create the client yourself and paste the credentials.",
    },
    category: "Email",
    blurb: "Google's email service.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: true,
    mcpName: "gmail (composio / google)",
    mcpTransport: "http",
    docsUrl: "https://developers.google.com/gmail/api",
    developerPortalUrl: "https://console.cloud.google.com/apis/credentials",
    oauthAuthorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["gmail.readonly", "gmail.send", "gmail.modify"],
    entities: ["Message", "Thread", "Label", "Draft"],
    outbound: ["create_draft", "send_message", "label_thread", "search_threads"],
    quirks: ["Inbound via Pub/Sub push (watch()) or polling history.", "Requires Google Cloud OAuth consent screen; sensitive scopes need verification."],
  },
  {
    match: ["google calendar", "gcal", "calendar.google.com"],
    appName: "Google Calendar",
    portalAutomation: {
      risk: "medium",
      allowAutomation: true,
      caveat:
        "NodeWorm can drive your own Google Cloud Console to create the OAuth client. Google's API terms allow this as long as you act as yourself (no masked identity), but Google's login bot-detection may challenge an automated session and the flow is unsupported. Proceed on your own account, or create the client yourself and paste the credentials.",
    },
    category: "Calendar",
    blurb: "Google's scheduling and calendar service.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: true,
    mcpName: "google-calendar",
    mcpTransport: "http",
    docsUrl: "https://developers.google.com/calendar/api",
    developerPortalUrl: "https://console.cloud.google.com/apis/credentials",
    oauthAuthorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    oauthTokenUrl: "https://oauth2.googleapis.com/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["calendar.events", "calendar.readonly"],
    entities: ["Event", "Calendar"],
    outbound: ["create_event", "update_event", "list_events", "respond_to_event"],
    quirks: ["Push notifications via watch channels; channels expire and must be renewed."],
  },
  {
    match: ["ticktick", "tick tick", "ticktick.com"],
    appName: "TickTick",
    category: "Tasks / Productivity",
    blurb: "Cross-platform to-do list and task manager.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: false,
    docsUrl: "https://developer.ticktick.com/docs",
    developerPortalUrl: "https://developer.ticktick.com/manage",
    oauthAuthorizeUrl: "https://ticktick.com/oauth/authorize",
    oauthTokenUrl: "https://ticktick.com/oauth/token",
    hasWebhooks: false,
    rateLimited: true,
    scopes: ["tasks:read", "tasks:write"],
    entities: ["Task", "Project", "Tag"],
    outbound: ["create_task", "complete_task", "list_projects", "update_task"],
    quirks: [
      "No hosted MCP: build a custom one over the REST API.",
      "No webhooks: bidirectional sync is achieved by mirroring tasks as entities and polling.",
      "OAuth app must register an exact redirect URI.",
    ],
  },
  {
    match: ["plaud", "plaud.ai", "plaud note"],
    appName: "Plaud",
    category: "Voice / Recording",
    blurb: "AI voice recorder and note device.",
    hasPublicApi: false,
    apiType: "none",
    authType: "browser",
    authMethods: ["browser"],
    hasHostedMcp: false,
    docsUrl: "https://www.plaud.ai",
    hasWebhooks: false,
    rateLimited: false,
    ipRestricted: true,
    twoFactor: false,
    entities: ["Recording", "Transcript", "Summary"],
    outbound: ["pull_recording", "pull_transcript"],
    quirks: [
      "No public API. The platform OAuth is locked to first-party clients.",
      "Workaround: drive the web app via a local npx headless session and mirror new recordings.",
      "Cloudflare bot protection (error 1010) blocks naive requests; use a real browser UA.",
    ],
  },
  {
    match: ["telegram", "telegram.org"],
    appName: "Telegram",
    category: "Messaging",
    blurb: "Cloud-based instant messaging.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "apikey",
    authMethods: ["apikey"],
    hasHostedMcp: false,
    docsUrl: "https://core.telegram.org/bots/api",
    developerPortalUrl: "https://t.me/BotFather",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["bot:send", "bot:receive"],
    entities: ["Message", "Chat", "Update"],
    outbound: ["send_message", "send_document", "answer_callback"],
    quirks: ["Bot token from BotFather acts as the API key.", "Inbound via setWebhook or long-poll getUpdates."],
  },
  {
    match: ["github", "github.com"],
    appName: "GitHub",
    category: "Dev / Source",
    blurb: "Code hosting and collaboration.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: true,
    mcpName: "github (official)",
    mcpTransport: "http",
    docsUrl: "https://docs.github.com/rest",
    developerPortalUrl: "https://github.com/settings/developers",
    oauthAuthorizeUrl: "https://github.com/login/oauth/authorize",
    oauthTokenUrl: "https://github.com/login/oauth/access_token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["repo", "issues:write", "pull_requests:write"],
    entities: ["Repo", "Issue", "PullRequest", "Commit"],
    outbound: ["create_issue", "open_pr", "comment", "merge_pr"],
    quirks: ["Fine-grained PATs or a GitHub App give least-privilege access.", "Rich webhook events for inbound."],
  },
  {
    match: ["linear", "linear.app"],
    appName: "Linear",
    category: "Project Management",
    blurb: "Issue tracking for software teams.",
    hasPublicApi: true,
    apiType: "graphql",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: true,
    mcpName: "linear (official)",
    mcpTransport: "http",
    docsUrl: "https://developers.linear.app/docs",
    developerPortalUrl: "https://linear.app/settings/api",
    oauthAuthorizeUrl: "https://linear.app/oauth/authorize",
    oauthTokenUrl: "https://api.linear.app/oauth/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["read", "write", "issues:create"],
    entities: ["Issue", "Project", "Team", "Cycle"],
    outbound: ["create_issue", "update_issue", "add_comment", "list_issues"],
    quirks: ["GraphQL API: outbound tools wrap queries and mutations.", "Webhooks for inbound."],
  },
  {
    match: ["hubspot", "hubspot.com"],
    appName: "HubSpot",
    category: "CRM",
    blurb: "CRM, marketing and sales platform.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: true,
    mcpName: "hubspot (official)",
    mcpTransport: "http",
    docsUrl: "https://developers.hubspot.com/docs/api/overview",
    developerPortalUrl: "https://app.hubspot.com/developer",
    oauthAuthorizeUrl: "https://app.hubspot.com/oauth/authorize",
    oauthTokenUrl: "https://api.hubapi.com/oauth/v1/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["crm.objects.contacts.write", "crm.objects.deals.write"],
    entities: ["Contact", "Company", "Deal", "Ticket"],
    outbound: ["create_contact", "update_deal", "log_activity", "search_contacts"],
  },
  {
    match: ["salesforce", "salesforce.com", "sfdc"],
    appName: "Salesforce",
    portalAutomation: {
      risk: "blocked",
      allowAutomation: false,
      caveat:
        "Salesforce disabled new Connected App creation in Spring '26 (UI and API both), so NodeWorm can't automate it. Use an External Client App, install via a managed package, or ask Salesforce Support to enable Connected Apps for your org, then paste the credentials here.",
    },
    category: "CRM",
    blurb: "Enterprise CRM platform.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: false,
    docsUrl: "https://developer.salesforce.com/docs/apis",
    developerPortalUrl: "https://developer.salesforce.com",
    oauthAuthorizeUrl: "https://login.salesforce.com/services/oauth2/authorize",
    oauthTokenUrl: "https://login.salesforce.com/services/oauth2/token",
    hasWebhooks: true,
    rateLimited: true,
    ipRestricted: true,
    scopes: ["api", "refresh_token"],
    entities: ["Account", "Contact", "Opportunity", "Lead"],
    outbound: ["create_lead", "update_opportunity", "soql_query"],
    quirks: ["Connected App + IP relaxation often required.", "No hosted MCP: build one over the REST/SOQL API."],
  },
  {
    match: ["airtable", "airtable.com"],
    appName: "Airtable",
    category: "Database / Spreadsheet",
    blurb: "Spreadsheet-database hybrid.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: false,
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    developerPortalUrl: "https://airtable.com/create/tokens",
    oauthAuthorizeUrl: "https://airtable.com/oauth2/v1/authorize",
    oauthTokenUrl: "https://airtable.com/oauth2/v1/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["data.records:read", "data.records:write"],
    entities: ["Base", "Table", "Record"],
    outbound: ["create_record", "update_record", "list_records"],
    quirks: ["Personal access tokens replace legacy API keys.", "Webhooks per base for inbound."],
  },
  {
    match: ["shopify", "shopify.com"],
    appName: "Shopify",
    portalAutomation: {
      risk: "low",
      allowAutomation: true,
      caveat:
        "NodeWorm can drive your own Shopify Partner dashboard to create this app. Shopify's terms do not prohibit automating your own partner account, but automated sessions are unsupported and could be flagged by anti-bot checks. Proceed on your own account, or create the app yourself and paste the keys.",
    },
    category: "E-commerce",
    blurb: "Commerce platform for online stores.",
    hasPublicApi: true,
    apiType: "graphql",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: false,
    docsUrl: "https://shopify.dev/docs/api",
    developerPortalUrl: "https://partners.shopify.com",
    oauthAuthorizeUrl: "https://{shop}.myshopify.com/admin/oauth/authorize",
    oauthTokenUrl: "https://{shop}.myshopify.com/admin/oauth/access_token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["read_orders", "write_products", "read_customers"],
    entities: ["Order", "Product", "Customer", "Fulfillment"],
    outbound: ["create_product", "fulfill_order", "list_orders"],
  },
  {
    match: ["quickbooks", "qbo", "quickbooks.intuit.com"],
    appName: "QuickBooks Online",
    portalAutomation: {
      risk: "medium",
      allowAutomation: true,
      caveat:
        "NodeWorm can drive your own Intuit Developer portal to create this app. Intuit does not specifically prohibit automating your own account, but it monitors actively and can suspend at its discretion, so treat this as unsupported and accept a small account risk. Safer option: create the app yourself and paste the client id and secret.",
    },
    category: "Accounting",
    blurb: "Cloud accounting for small business.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: false,
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/get-started",
    developerPortalUrl: "https://developer.intuit.com",
    oauthAuthorizeUrl: "https://appcenter.intuit.com/connect/oauth2",
    oauthTokenUrl: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["com.intuit.quickbooks.accounting"],
    entities: ["Invoice", "Customer", "Bill", "Payment"],
    outbound: ["create_invoice", "record_payment", "list_customers"],
    quirks: ["Own developer app required; sandbox vs production realms."],
  },
  {
    match: ["xero", "xero.com"],
    appName: "Xero",
    portalAutomation: {
      risk: "high",
      allowAutomation: false,
      caveat:
        "Heads up: Xero's developer terms specifically restrict using bots or browser automation to simulate user actions on its sites without authorisation, so automating even your own developer portal may breach those terms and risk your account. NodeWorm recommends you create the Xero app yourself and paste the client id and secret. Only enable automation if you accept that risk on your own account.",
    },
    category: "Accounting",
    blurb: "Cloud accounting software.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2"],
    hasHostedMcp: false,
    docsUrl: "https://developer.xero.com/documentation",
    developerPortalUrl: "https://developer.xero.com/app/manage",
    oauthAuthorizeUrl: "https://login.xero.com/identity/connect/authorize",
    oauthTokenUrl: "https://identity.xero.com/connect/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["accounting.transactions", "accounting.contacts"],
    entities: ["Invoice", "Contact", "Account", "Payment"],
    outbound: ["create_invoice", "create_contact", "list_invoices"],
  },
  {
    match: ["twilio", "twilio.com"],
    appName: "Twilio",
    category: "Comms / SMS",
    blurb: "Programmable SMS, voice and messaging.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "apikey",
    authMethods: ["apikey"],
    hasHostedMcp: false,
    docsUrl: "https://www.twilio.com/docs/usage/api",
    developerPortalUrl: "https://console.twilio.com",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["sms:send", "calls:create"],
    entities: ["Message", "Call", "PhoneNumber"],
    outbound: ["send_sms", "make_call", "list_messages"],
    quirks: ["Account SID + auth token; inbound via webhook on the number."],
  },
  {
    match: ["discord", "discord.com"],
    appName: "Discord",
    category: "Messaging",
    blurb: "Voice, video and text community chat.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: false,
    docsUrl: "https://discord.com/developers/docs",
    developerPortalUrl: "https://discord.com/developers/applications",
    oauthAuthorizeUrl: "https://discord.com/oauth2/authorize",
    oauthTokenUrl: "https://discord.com/api/oauth2/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["bot", "messages.read"],
    entities: ["Guild", "Channel", "Message", "Member"],
    outbound: ["send_message", "create_channel", "add_role"],
    quirks: ["Bot token or OAuth; Gateway websocket for realtime inbound."],
  },
  {
    match: ["calendly", "calendly.com"],
    appName: "Calendly",
    category: "Scheduling",
    blurb: "Automated scheduling and booking.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: false,
    docsUrl: "https://developer.calendly.com",
    developerPortalUrl: "https://calendly.com/integrations/api_webhooks",
    oauthAuthorizeUrl: "https://auth.calendly.com/oauth/authorize",
    oauthTokenUrl: "https://auth.calendly.com/oauth/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["default"],
    entities: ["Event", "Invitee", "EventType"],
    outbound: ["list_events", "cancel_event", "get_invitee"],
  },
  {
    match: ["jira", "atlassian", "jira.com"],
    appName: "Jira",
    category: "Project Management",
    blurb: "Issue and project tracking by Atlassian.",
    hasPublicApi: true,
    apiType: "rest",
    authType: "oauth2",
    authMethods: ["oauth2", "apikey"],
    hasHostedMcp: true,
    mcpName: "atlassian (official)",
    mcpTransport: "http",
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/rest",
    developerPortalUrl: "https://developer.atlassian.com/console/myapps",
    oauthAuthorizeUrl: "https://auth.atlassian.com/authorize",
    oauthTokenUrl: "https://auth.atlassian.com/oauth/token",
    hasWebhooks: true,
    rateLimited: true,
    scopes: ["read:jira-work", "write:jira-work"],
    entities: ["Issue", "Project", "Sprint", "Board"],
    outbound: ["create_issue", "transition_issue", "add_comment"],
  },
  {
    match: ["signal", "signal messenger", "signal.org"],
    appName: "Signal",
    category: "Messaging",
    blurb: "Private encrypted messaging and calling.",
    hasPublicApi: false,
    apiType: "none",
    authType: "browser",
    authMethods: ["browser"],
    hasHostedMcp: false,
    docsUrl: "https://signal.org/download/",
    noWebClient: true,
    hasWebhooks: false,
    rateLimited: false,
    entities: ["Message", "Contact", "Thread", "Attachment"],
    outbound: ["send_message", "read_messages", "list_contacts"],
    quirks: [
      "Signal has NO browser login (no web client), so it cannot be connected by signing in. A device links only through a signal-cli bridge that generates the linking QR.",
      "When a Signal bridge is configured (SIGNAL_BRIDGE_URL), NodeWorm hosts signal-cli-rest-api for you: scan the device-link QR once and NodeWorm verifies + holds the linked number encrypted. Technical users can self-host the bridge instead.",
    ],
  },
  {
    match: ["whatsapp", "whatsapp messenger", "whatsapp.com", "wa.me"],
    appName: "WhatsApp",
    category: "Messaging",
    blurb: "Meta's encrypted messaging platform.",
    hasPublicApi: false,
    apiType: "none",
    authType: "browser",
    authMethods: ["browser"],
    hasHostedMcp: false,
    docsUrl: "https://faq.whatsapp.com/",
    loginUrl: "https://web.whatsapp.com",
    hasWebhooks: false,
    rateLimited: false,
    entities: ["Message", "Contact", "Chat", "Group"],
    outbound: ["send_message", "read_messages", "list_chats"],
    quirks: [
      "No public API for personal accounts. WhatsApp Web (web.whatsapp.com) is a real QR-link web client: NodeWorm opens it, the user scans the QR once, and NodeWorm drives the web interface for all reads and sends.",
      "WhatsApp Business API exists but requires Meta approval and a business account.",
    ],
  },
  {
    match: ["telegram", "telegram messenger", "t.me", "telegram.org"],
    appName: "Telegram",
    category: "Messaging",
    blurb: "Cloud-based messaging with bots and channels.",
    hasPublicApi: false,
    apiType: "none",
    authType: "browser",
    authMethods: ["browser"],
    hasHostedMcp: false,
    docsUrl: "https://core.telegram.org/",
    loginUrl: "https://web.telegram.org",
    hasWebhooks: false,
    rateLimited: false,
    entities: ["Message", "Chat", "User", "Channel"],
    outbound: ["send_message", "read_messages", "list_chats"],
    quirks: [
      "Telegram Web (web.telegram.org) is a real web client: NodeWorm opens it, the user signs in once (phone code or QR), and NodeWorm drives the web interface. (The Bot API is a separate developer path for bots only.)",
    ],
  },
];

export function lookup(query: string): KnowledgeEntry | undefined {
  const q = query.trim().toLowerCase();
  if (!q) return undefined;
  // Prefer exact name/domain match, then substring.
  let best: KnowledgeEntry | undefined;
  for (const e of KNOWLEDGE) {
    for (const m of e.match) {
      if (q === m) return e;
      if (!best && (q.includes(m) || m.includes(q))) best = e;
    }
  }
  return best;
}
