// Connectors authored from each vendor's OWN public API documentation. These are
// not derivative works: endpoints and field names are factual API surface, so no
// third-party licence or attribution attaches (contrast hubspot.ts, which IS
// adapted from Activepieces MIT source and carries its notice and pinned commit).
//
// Scope rule: only JSON APIs with a CONCRETE base URL belong here. The flow http
// step sends application/json, so form-encoded APIs (Stripe) are excluded, as are
// per-tenant templated hosts (Shopify, Mailchimp) until the step model carries a
// per-connection base. Both are noted in PLAN.md rather than half-supported.

import type { PieceDefinition } from "./types";

const docs = (docsUrl: string) => ({ origin: "vendor-docs" as const, docsUrl });

export const VENDOR_PIECES: PieceDefinition[] = [
  {
    id: "slack",
    name: "Slack",
    category: "messaging",
    apiBase: "https://slack.com/api",
    auth: { type: "oauth2", authorizeUrl: "https://slack.com/oauth/v2/authorize", tokenUrl: "https://slack.com/api/oauth.v2.access", scopes: ["chat:write", "channels:read", "channels:history"], scopeSep: "," },
    props: [{ key: "channel", label: "Channel ID", type: "text", required: true }],
    actions: [
      { key: "post_message", name: "Send a message", description: "Post a message to a channel", method: "post", path: "/chat.postMessage", bodyKeys: ["channel", "text"] },
      { key: "list_channels", name: "List channels", description: "List conversations", method: "get", path: "/conversations.list" },
      { key: "post_reply", name: "Reply in thread", description: "Reply to a thread", method: "post", path: "/chat.postMessage", bodyKeys: ["channel", "text", "thread_ts"] },
    ],
    triggers: [{ key: "new_message", name: "New message", type: "webhook", event: "message posted" }],
    upstream: docs("https://api.slack.com/methods"),
  },
  {
    id: "notion",
    name: "Notion",
    category: "productivity",
    apiBase: "https://api.notion.com/v1",
    auth: { type: "oauth2", authorizeUrl: "https://api.notion.com/v1/oauth/authorize", tokenUrl: "https://api.notion.com/v1/oauth/token", scopes: [] },
    props: [{ key: "databaseId", label: "Database ID", type: "text", required: true }],
    actions: [
      { key: "create_page", name: "Create a page", description: "Add a page to a database", method: "post", path: "/pages", bodyKeys: ["parent", "properties"] },
      { key: "query_database", name: "Find pages in a database", description: "Query a database", method: "post", path: "/databases/{databaseId}/query", bodyKeys: ["filter", "sorts"] },
      { key: "update_page", name: "Update a page", description: "Update page properties", method: "patch", path: "/pages/{pageId}", bodyKeys: ["properties"] },
      { key: "search", name: "Search", description: "Search pages and databases", method: "post", path: "/search", bodyKeys: ["query"] },
    ],
    triggers: [{ key: "new_page", name: "New page in database", type: "polling", itemsPath: "results", idPath: "id" }],
    upstream: docs("https://developers.notion.com/reference"),
  },
  {
    id: "github",
    name: "GitHub",
    category: "dev",
    apiBase: "https://api.github.com",
    auth: { type: "oauth2", authorizeUrl: "https://github.com/login/oauth/authorize", tokenUrl: "https://github.com/login/oauth/access_token", scopes: ["repo"], scopeSep: " " },
    props: [{ key: "repo", label: "Repository (owner/name)", type: "text", required: true }],
    actions: [
      { key: "create_issue", name: "Create an issue", description: "Open an issue", method: "post", path: "/repos/{repo}/issues", bodyKeys: ["title", "body", "labels"] },
      { key: "comment_issue", name: "Comment on an issue", description: "Add a comment", method: "post", path: "/repos/{repo}/issues/{issueNumber}/comments", bodyKeys: ["body"] },
      { key: "list_issues", name: "List issues", description: "List repository issues", method: "get", path: "/repos/{repo}/issues" },
      { key: "close_issue", name: "Close an issue", description: "Set an issue to closed", method: "patch", path: "/repos/{repo}/issues/{issueNumber}", bodyKeys: ["state"] },
    ],
    triggers: [{ key: "new_issue", name: "New issue", type: "webhook", event: "issues" }],
    upstream: docs("https://docs.github.com/en/rest"),
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "productivity",
    apiBase: "https://api.airtable.com/v0",
    auth: { type: "oauth2", authorizeUrl: "https://airtable.com/oauth2/v1/authorize", tokenUrl: "https://airtable.com/oauth2/v1/token", scopes: ["data.records:read", "data.records:write"], scopeSep: " " },
    props: [
      { key: "baseId", label: "Base ID", type: "text", required: true },
      { key: "tableName", label: "Table name", type: "text", required: true },
    ],
    actions: [
      { key: "create_record", name: "Create a record", description: "Add a record to a table", method: "post", path: "/{baseId}/{tableName}", bodyKeys: ["fields"] },
      { key: "list_records", name: "List records", description: "List records in a table", method: "get", path: "/{baseId}/{tableName}" },
      { key: "update_record", name: "Update a record", description: "Update a record by id", method: "patch", path: "/{baseId}/{tableName}/{recordId}", bodyKeys: ["fields"] },
    ],
    triggers: [{ key: "new_record", name: "New record", type: "polling", itemsPath: "records", idPath: "id" }],
    upstream: docs("https://airtable.com/developers/web/api/introduction"),
  },
  {
    id: "linear",
    name: "Linear",
    category: "dev",
    apiBase: "https://api.linear.app",
    auth: { type: "oauth2", authorizeUrl: "https://linear.app/oauth/authorize", tokenUrl: "https://api.linear.app/oauth/token", scopes: ["read", "write"], scopeSep: "," },
    props: [{ key: "teamId", label: "Team ID", type: "text" }],
    actions: [{ key: "graphql", name: "Run a Linear query", description: "Create or fetch issues via GraphQL", method: "post", path: "/graphql", bodyKeys: ["query", "variables"] }],
    triggers: [{ key: "new_issue", name: "New issue", type: "webhook", event: "Issue create" }],
    upstream: docs("https://developers.linear.app/docs/graphql/working-with-the-graphql-api"),
  },
  {
    id: "asana",
    name: "Asana",
    category: "productivity",
    apiBase: "https://app.asana.com/api/1.0",
    auth: { type: "oauth2", authorizeUrl: "https://app.asana.com/-/oauth_authorize", tokenUrl: "https://app.asana.com/-/oauth_token", scopes: ["default"], scopeSep: " " },
    props: [{ key: "projectId", label: "Project ID", type: "text" }],
    actions: [
      { key: "create_task", name: "Create a task", description: "Create a task", method: "post", path: "/tasks", bodyKeys: ["data"] },
      { key: "list_tasks", name: "List tasks", description: "List tasks in a project", method: "get", path: "/projects/{projectId}/tasks" },
      { key: "complete_task", name: "Complete a task", description: "Mark a task complete", method: "put", path: "/tasks/{taskId}", bodyKeys: ["data"] },
    ],
    triggers: [{ key: "new_task", name: "New task", type: "polling", itemsPath: "data", idPath: "gid" }],
    upstream: docs("https://developers.asana.com/reference/rest-api-reference"),
  },
  {
    id: "discord",
    name: "Discord",
    category: "messaging",
    apiBase: "https://discord.com/api/v10",
    auth: { type: "oauth2", authorizeUrl: "https://discord.com/oauth2/authorize", tokenUrl: "https://discord.com/api/oauth2/token", scopes: ["bot", "identify"], scopeSep: " " },
    props: [{ key: "channelId", label: "Channel ID", type: "text", required: true }],
    actions: [
      { key: "send_message", name: "Send a message", description: "Post to a channel", method: "post", path: "/channels/{channelId}/messages", bodyKeys: ["content"] },
      { key: "list_messages", name: "List messages", description: "Read recent messages", method: "get", path: "/channels/{channelId}/messages" },
    ],
    triggers: [{ key: "new_message", name: "New message", type: "polling", itemsPath: "", idPath: "id" }],
    upstream: docs("https://discord.com/developers/docs/resources/channel"),
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    category: "productivity",
    apiBase: "https://sheets.googleapis.com/v4",
    auth: { type: "oauth2", authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: ["https://www.googleapis.com/auth/spreadsheets"], scopeSep: " " },
    props: [
      { key: "spreadsheetId", label: "Spreadsheet ID", type: "text", required: true },
      { key: "range", label: "Range (e.g. Sheet1!A:D)", type: "text", required: true },
    ],
    actions: [
      { key: "append_row", name: "Add a row", description: "Append values to a sheet", method: "post", path: "/spreadsheets/{spreadsheetId}/values/{range}:append", bodyKeys: ["values"] },
      { key: "read_rows", name: "Read rows", description: "Read a range of values", method: "get", path: "/spreadsheets/{spreadsheetId}/values/{range}" },
      { key: "update_rows", name: "Update rows", description: "Write values to a range", method: "put", path: "/spreadsheets/{spreadsheetId}/values/{range}", bodyKeys: ["values"] },
    ],
    triggers: [{ key: "new_row", name: "New row", type: "polling", itemsPath: "values", idPath: "0" }],
    upstream: docs("https://developers.google.com/sheets/api/reference/rest"),
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "scheduling",
    apiBase: "https://www.googleapis.com/calendar/v3",
    auth: { type: "oauth2", authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: ["https://www.googleapis.com/auth/calendar"], scopeSep: " " },
    props: [{ key: "calendarId", label: "Calendar ID", type: "text", required: true }],
    actions: [
      { key: "create_event", name: "Create an event", description: "Add an event to a calendar", method: "post", path: "/calendars/{calendarId}/events", bodyKeys: ["summary", "start", "end", "description"] },
      { key: "list_events", name: "List events", description: "List upcoming events", method: "get", path: "/calendars/{calendarId}/events" },
      { key: "delete_event", name: "Delete an event", description: "Remove an event", method: "delete", path: "/calendars/{calendarId}/events/{eventId}" },
    ],
    triggers: [{ key: "new_event", name: "New event", type: "polling", itemsPath: "items", idPath: "id" }],
    upstream: docs("https://developers.google.com/calendar/api/v3/reference"),
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "productivity",
    apiBase: "https://gmail.googleapis.com/gmail/v1",
    auth: { type: "oauth2", authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth", tokenUrl: "https://oauth2.googleapis.com/token", scopes: ["https://www.googleapis.com/auth/gmail.modify"], scopeSep: " " },
    props: [],
    actions: [
      { key: "send_message", name: "Send an email", description: "Send a message", method: "post", path: "/users/me/messages/send", bodyKeys: ["raw"] },
      { key: "list_messages", name: "Find emails", description: "List messages", method: "get", path: "/users/me/messages" },
      { key: "get_message", name: "Read an email", description: "Fetch a message", method: "get", path: "/users/me/messages/{messageId}" },
    ],
    triggers: [{ key: "new_email", name: "New email", type: "polling", itemsPath: "messages", idPath: "id" }],
    upstream: docs("https://developers.google.com/gmail/api/reference/rest"),
  },
  {
    id: "typeform",
    name: "Typeform",
    category: "marketing",
    apiBase: "https://api.typeform.com",
    auth: { type: "oauth2", authorizeUrl: "https://api.typeform.com/oauth/authorize", tokenUrl: "https://api.typeform.com/oauth/token", scopes: ["forms:read", "responses:read"], scopeSep: " " },
    props: [{ key: "formId", label: "Form ID", type: "text", required: true }],
    actions: [
      { key: "list_responses", name: "Get form responses", description: "List responses for a form", method: "get", path: "/forms/{formId}/responses" },
      { key: "list_forms", name: "List forms", description: "List your forms", method: "get", path: "/forms" },
    ],
    triggers: [{ key: "new_response", name: "New response", type: "webhook", event: "form_response" }],
    upstream: docs("https://www.typeform.com/developers/get-started/"),
  },
  {
    id: "calendly",
    name: "Calendly",
    category: "scheduling",
    apiBase: "https://api.calendly.com",
    auth: { type: "oauth2", authorizeUrl: "https://auth.calendly.com/oauth/authorize", tokenUrl: "https://auth.calendly.com/oauth/token", scopes: [], scopeSep: " " },
    props: [],
    actions: [
      { key: "list_events", name: "List scheduled events", description: "List booked events", method: "get", path: "/scheduled_events" },
      { key: "get_me", name: "Get my details", description: "Fetch the current user", method: "get", path: "/users/me" },
    ],
    triggers: [{ key: "new_booking", name: "New booking", type: "webhook", event: "invitee.created" }],
    upstream: docs("https://developer.calendly.com/api-docs"),
  },
  {
    id: "zoom",
    name: "Zoom",
    category: "scheduling",
    apiBase: "https://api.zoom.us/v2",
    auth: { type: "oauth2", authorizeUrl: "https://zoom.us/oauth/authorize", tokenUrl: "https://zoom.us/oauth/token", scopes: ["meeting:write", "meeting:read"], scopeSep: " " },
    props: [],
    actions: [
      { key: "create_meeting", name: "Create a meeting", description: "Schedule a meeting", method: "post", path: "/users/me/meetings", bodyKeys: ["topic", "start_time", "duration"] },
      { key: "list_meetings", name: "List meetings", description: "List your meetings", method: "get", path: "/users/me/meetings" },
    ],
    triggers: [{ key: "meeting_ended", name: "Meeting ended", type: "webhook", event: "meeting.ended" }],
    upstream: docs("https://developers.zoom.us/docs/api/"),
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "crm",
    apiBase: "https://api.intercom.io",
    auth: { type: "oauth2", authorizeUrl: "https://app.intercom.com/oauth", tokenUrl: "https://api.intercom.io/auth/eagle/token", scopes: [] },
    props: [],
    actions: [
      { key: "create_contact", name: "Create a contact", description: "Create a contact", method: "post", path: "/contacts", bodyKeys: ["email", "name"] },
      { key: "search_contacts", name: "Find contacts", description: "Search contacts", method: "post", path: "/contacts/search", bodyKeys: ["query"] },
      { key: "send_message", name: "Send a message", description: "Send a message to a contact", method: "post", path: "/messages", bodyKeys: ["message_type", "body", "from", "to"] },
    ],
    triggers: [{ key: "new_conversation", name: "New conversation", type: "webhook", event: "conversation.user.created" }],
    upstream: docs("https://developers.intercom.com/docs/references/rest-api/"),
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "crm",
    apiBase: "https://api.pipedrive.com/v1",
    auth: { type: "oauth2", authorizeUrl: "https://oauth.pipedrive.com/oauth/authorize", tokenUrl: "https://oauth.pipedrive.com/oauth/token", scopes: [], scopeSep: " " },
    props: [],
    actions: [
      { key: "create_deal", name: "Create a deal", description: "Add a deal", method: "post", path: "/deals", bodyKeys: ["title", "value", "currency"] },
      { key: "create_person", name: "Create a person", description: "Add a person", method: "post", path: "/persons", bodyKeys: ["name", "email"] },
      { key: "list_deals", name: "List deals", description: "List deals", method: "get", path: "/deals" },
    ],
    triggers: [{ key: "new_deal", name: "New deal", type: "polling", itemsPath: "data", idPath: "id" }],
    upstream: docs("https://developers.pipedrive.com/docs/api/v1"),
  },
  {
    id: "todoist",
    name: "Todoist",
    category: "productivity",
    apiBase: "https://api.todoist.com/rest/v2",
    auth: { type: "oauth2", authorizeUrl: "https://todoist.com/oauth/authorize", tokenUrl: "https://todoist.com/oauth/access_token", scopes: ["data:read_write"], scopeSep: "," },
    props: [],
    actions: [
      { key: "create_task", name: "Create a task", description: "Add a task", method: "post", path: "/tasks", bodyKeys: ["content", "due_string", "project_id"] },
      { key: "list_tasks", name: "List tasks", description: "List active tasks", method: "get", path: "/tasks" },
      { key: "close_task", name: "Complete a task", description: "Close a task", method: "post", path: "/tasks/{taskId}/close" },
    ],
    triggers: [{ key: "new_task", name: "New task", type: "polling", itemsPath: "", idPath: "id" }],
    upstream: docs("https://developer.todoist.com/rest/v2/"),
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "productivity",
    apiBase: "https://api.clickup.com/api/v2",
    auth: { type: "oauth2", authorizeUrl: "https://app.clickup.com/api", tokenUrl: "https://api.clickup.com/api/v2/oauth/token", scopes: [] },
    props: [{ key: "listId", label: "List ID", type: "text", required: true }],
    actions: [
      { key: "create_task", name: "Create a task", description: "Add a task to a list", method: "post", path: "/list/{listId}/task", bodyKeys: ["name", "description"] },
      { key: "list_tasks", name: "List tasks", description: "List tasks in a list", method: "get", path: "/list/{listId}/task" },
    ],
    triggers: [{ key: "new_task", name: "New task", type: "polling", itemsPath: "tasks", idPath: "id" }],
    upstream: docs("https://developer.clickup.com/reference"),
  },
  {
    id: "monday",
    name: "Monday",
    category: "productivity",
    apiBase: "https://api.monday.com",
    auth: { type: "oauth2", authorizeUrl: "https://auth.monday.com/oauth2/authorize", tokenUrl: "https://auth.monday.com/oauth2/token", scopes: ["boards:read", "boards:write"], scopeSep: " " },
    props: [{ key: "boardId", label: "Board ID", type: "text" }],
    actions: [{ key: "graphql", name: "Run a Monday query", description: "Create or fetch items via GraphQL", method: "post", path: "/v2", bodyKeys: ["query", "variables"] }],
    triggers: [{ key: "new_item", name: "New item", type: "webhook", event: "create_item" }],
    upstream: docs("https://developer.monday.com/api-reference/docs"),
  },
];
